services:
  - docker
env:
  global:
    # should change to yours
    - secure: "BRam2gCt2YFOcec1eIKf3/znHxv+a2Yi+dPMeNcTstNsonU0IyEhRKHsWLRgZ5DxQTnmoH212cJfBwKmf6kVTcg8UcVipTdrlzMKR/mAZ6ben4rrnbJQE2XmvKCQz2FciUgILB7Ls3zgiSunYow2moU2Ivc3ZP/9XNagGKcXO2x+PMjikC9jUfE6YYiepobwVTv31L+NoBWaSSkLB/Mud0P4bv/uNwNfxvOEigP+gbR+OawQatAs1k+MpbtmN58iEMkTyxSQ4O172atM0AUJCzi6Hc9kwRB/JIQEdBLLIrV5NihFORJIXgjooLo2VMF9kiRjwH/Du94KHCy6hy+3MslgXR7y/GtbcvRbKatZKhu0kEFEKu9VN5vGpMrQyTwsEKnoX2ewSzlUSc/QS2GISSjUqpFaJvhY+jd8r0ZC1yiOSncHKaa1jvNkMdutS8Ur3SU8VK5HBkZXq15lHALZqvGGrtb3jUYrWMmWAUth+wQab2DMHWDqnr9DbMrwQnR5sCDr4qqazD+adZpGYgSFOssVion2P1Q79yVPpfJYzMtybY005oul6YBQIstDfzIGMie8CkCpZvY1NHmuDB25cdZ9v6VG+bvQVwn1KftaSbj5BVrghhWwLQY+JK7vwHO/x9+9pbPXc8YMbBKCkpt8icgPTyYaZMbnp6bfjB09olA="
before_install:
  - echo "Login into heroku"
  - heroku container:login
jobs:
  include:
    - stage: push
      script:
        - docker build -t ch4-web:latest -f ./Dockerfile .
        # should change to yours
        - docker tag ch4-web:latest registry.heroku.com/advance-tech-ch4/web
        # should change to yours
        - docker push registry.heroku.com/advance-tech-ch4/web
      deploy:
        - provider: script
          # should change to yours
          script: heroku container:release web --app advance-tech-ch4
          on: # 不設這個 預設只有在 master branch 會做 deploy
            branch: main
