services:
  - docker
env:
  global:
    # should change to yours
    - secure: "m3crwM66BU7LZ3SifohUGNtxiKvr1Q8I4s/XIvr+jzauGcuIf8XDZj1uA4KV35RRS2HzjV1BANmXbSmG0hF6djoerQWYjzrVAJuTFuZLFQzJORrSAfeQg7G8BNP+LZpQYNgXvz3tYrp9Y51mpE6BRv5GXvQ9xdiHTXMs2CO0DmELYRRVD7D8xXG9Ha2ZUd5LqsrSzv6C1HZF4JzdT4AClfJYCrF2Tj4YbIxXA8bx4FVLIetVIXX3pFa/mdvowEVb41vVAncDkRBDnQH0+MuR76xwyLnIxSdhZ1Q47IK8p0L8k6ma2uNg6S2eptUg3xi/6GN5d8yui1+Xq4GxyM1cuUs8V6DKL2FFw2P0n55MLFzkzSWrfkmJtvZoyMMlepH1YLHOQ3IOsUJym7zrzWRWqdEPLExibkYjeHnE6poMR7utsEhAphg46BE/VzYc5LCpLWqdjguWiAarFeF6leihy/lbZVt+x85Rmn8NSe3vrIkTl7EKAxH9r2VMUAj6e8QhJ09W12on2rnBOm0r50+tsE1zzKOOYnaPAefyvQCm/rpT2z/aC2Dl4MZWeRHUd6R4fVoWfCHnP5W8KTbcFavQ91ZRd/gZ9OfV2y3bNlXaPyZCQ/8DCiLbnWEC27W6Pe6UGA15X9jnIeibVJwmfhpRzU8N2RF6scSqRn1UccXwC8s="
before_install:
  - echo "Login into heroku"
  - heroku container:login
jobs:
  include:
    - stage: push
      script:
        - docker build -t ch4-web:latest -f ./Dockerfile .
        # should change to yours
        - docker tag ch4-web:latest registry.heroku.com/advance-tech-ch4/web
        # should change to yours
        - docker push registry.heroku.com/advance-tech-ch4/web
      deploy:
        - provider: script
          # should change to yours
          script: heroku container:release web --app advance-tech-ch4
          on: # 不設這個 預設只有在 master branch 會做 deploy
            branch: main
