services:
  - docker
env:
  global:
    # should change to yours
    - secure: "Dp6ktlFHmfOaF+PxAW//VSvuMwSfxoPneOko8InXTUgA9xkCqJDWJ9p+wyII0h86DbqzarXr6vKmItoor8u4RR9FgCzZkFiH5mMsZVhkshaSTlltIotOJmqqra6hAdhePD88VCyVd7rFMAPHcI9TrMq5vhouY92eQjHFtFrjrJK1ESZsfFfb8MUG9NvoDDF9rUYnTluUp6nZ7JLcPyYHxl52suBa10DAwgCRLyYI/5vizv7iAuVMrmqvVuoMeh2DZzzi0ZDLMKTuYfYO1Zgp2i8cTIpGeIztKD4LjRR1uYOIhwDBmBxk0GUk4e917xCaPaxvxJXVmeByga90mXn/608L3NdiGyN1X2k2jKVvkOmIWjOEYRLYwo1bCCc+dFf4V9lScy2VezdG50DmT21oR6yjgCBzEFk9dXy1DnYLh8ArRvh8aazgc5giaF7XWkZ/8dRm/8UOkfeaVLnyNrcsf46TVzwC5FGBgE3FDSFI3iMNIH/XlSUNJz0Q54G0WEBpodARr/IN0GCpOuiqmyc4xxN0o1VlP7S6tDOVoxhDxCvSHpt1u/LXY71MjSmFedXlWdoMdu4pwXykLxeNxk3FtuBdy688To4Jjbv0GPh1IsuVIbL0v7XcFgmg57e7rZEyI/4pqF4sikffBsSevow/PPkyJW8S1tOFhfXGzK3GE6c="
before_install:
  - echo "Login into heroku"
  - heroku container:login
jobs:
  include:
    - stage: push
      script:
        - docker build -t ch4-web:latest -f ./Dockerfile .
        # should change to yours
        - docker tag ch4-web:latest registry.heroku.com/ch4-test/web #
        # should change to yours
        - docker push registry.heroku.com/ch4-test/web #
      deploy:
        - provider: script
          # should change to yours
          script: heroku container:release web --app ch4-test #
          on: # 不設這個 預設只有在 master branch 會做 deploy
            branch: main
